// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// Replace this file by running from the repo root:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until then, placeholder values allow the app to build; Crashlytics will not
// report until configuration is complete. See docs/firebase_crashlytics_setup.md.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Firebase Crashlytics is not configured for web builds.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for $defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'UNCONFIGURED',
    appId: '1:0:android:0',
    messagingSenderId: '0',
    projectId: 'liuban-unconfigured',
    storageBucket: 'liuban-unconfigured.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'UNCONFIGURED',
    appId: '1:0:ios:0',
    messagingSenderId: '0',
    projectId: 'liuban-unconfigured',
    storageBucket: 'liuban-unconfigured.appspot.com',
    iosBundleId: 'com.example.liuban',
  );
}
